stages:
    - build_stage
    - test_stage
    - deploy_stage
# Building the backend project
build_backend:
    stage: build_stage
    image: maven:3.8.2-eclipse-temurin-17
    before_script:
        - cd backend
    script:
        - echo "Starting  - Maven Build stage"
        - mvn clean install # compile, package, and install
        - echo "Completed - Maven Build stage"
    artifacts:
        paths:
            - target/*.jar
# Executing tests in backend project
test_backend:
    stage: test_stage
    image: maven:3.8.2-eclipse-temurin-17
    before_script:
        - cd backend
    script:
        - echo "Starting  - Testing Maven Build"
        - mvn test
        - echo "Completed - Testing Maven Build"
    artifacts:
        paths:
            - target/*.jar
# Deploy the backend build on Render.com
deploy_backend:
    stage: deploy_stage
    before_script:
        - apt update
        - apt install curl -y
    script:
        - echo "Starting  - Deploying Springboot"
        - curl -s "https://api.render.com/deploy/srv-${RENDER_DEPLOY_KEY_1}?key=${RENDER_DEPLOY_KEY_2}" 
        - echo "Completed - Deploying Springboot"
    # Execute Deploy only when commits are made on production 'main' branch
    only:
        - main